services:
   inventaryentryandexitservice:
      image: "inventaryentryandexitservice"
      ports:
         - "22100:22100"
      container_name: inventaryentryandexitservice
      hostname: inventaryentryandexitservice
      stdin_open: true
      tty: true
      network_mode: "host"

   stocktransferservice:
      image: "stocktransferservice"
      ports:
         - "22101:22101"
      container_name: stocktransferservice
      hostname: stocktransferservice
      stdin_open: true
      tty: true
      network_mode: "host"
   defectrecord:
      image: "defectrecord"
      ports:
         - "22110:22110"
      container_name: defectrecord
      hostname: defectrecord
      stdin_open: true
      tty: true
      network_mode: "host"


